FROM node:18

WORKDIR /app

# Copy and install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Use .env if needed
# ENV NODE_ENV=production

EXPOSE 5000
CMD ["npm", "start"]
